# Generated by Django 5.0 on 2024-02-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
