# Generated by Django 5.0 on 2024-02-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment_approved"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "catagories"},
        ),
    ]
